jincde/Chicken-Kurly

- products/templates/products/index.html
- static/css/style.css
- templates/base.html
products index페이지 **전체구조** 구현
- 세부 디자인은 미완성
> feat(products/index) : products 인덱스 페이지 전체 구조 완성

- accounts/templates/accounts/profile.html
- accounts/templates/accounts/profile_update.html
docs: profile/profile_update 수정
> docs: profile/profile_update 수정

- PJT/urls.py
- accounts/templates/accounts/login.html
- accounts/views.py
- products/admin.py
- products/templates/products/detail.html
- products/templates/products/index.html
- products/urls.py
- products/views.py
`models.py`에서 `CartItem`, `DdibItem` 추가
> fix : products 장바구니 & 찜 Null 오류 수정

- PJT/urls.py
- accounts/templates/accounts/login.html
- products/templates/products/index.html
- static/css/style.css
- templates/base.html
- 회원가입/로그인 연결
- carousel 광고 추가(로고)
> feat : 회원가입/로그인 사이트 연결, carousel 광고 추가

- articles/models.py
- articles/templates/articles/index.html
- articles/urls.py
- articles/views.py
feat : article 댓글 작성 및 삭제 기능 구현
글 상세보기 모달창 안에
댓글 작성, 댓글 삭제 기능 추가
> feat : article 댓글 작성 및 삭제 기능 구현

- PJT/settings.py
- PJT/urls.py
- accounts/templates/accounts/login.html
- accounts/views.py
- templates/base.html
> chore: signup&login 수정

- products/templates/products/detail.html
- if 분기로
- 이미 찜이 되어 있으면 색칠된 별
- 찜이 되어 있지 않으면 테두리만 있는 별
> chore : product 찜 별 아이콘으로 변경(주석)

- accounts/templates/accounts/profile.html
- static/css/style.css
- templates/base.html
- 컨텐츠 기획 필요
- ex) 누적금액, 구매횟수 등
> feat : accounts/detail 스타일

- articles/templates/articles/create.html
- articles/templates/articles/index.html
- products/views.py
style: articles 자유게시판 인덱스 페이지 수정
디자인 변경
> style: articles 자유게시판 인덱스 페이지 수정

- products/templates/products/detail.html
- products/views.py
- static/css/products/review.css
**추후에 구현할 예정**
- 페이지네이션
- 이미지 팝오버
> feat(products) 상품 후기 이미지 보이도록 함

- articles/models.py
- articles/templates/articles/create.html
- articles/templates/articles/detail.html
- articles/views.py
- templates/base.html
feature : articles app 자유게시판 상세페이지 댓글 페이지네이션 기능 구현 완료
> feature : articles app 자유게시판 상세페이지 댓글 페이지네이션 기능 구현 완료

- articles/templates/articles/detail.html
- articles/templates/articles/index.html
- articles/views.py
fix : articles app 자유게시판 좋아요 버튼 버그 수정 및 자잘한 코드수정
1. 다른 게시글의 좋아요를 눌러도 맨위의 게시판도 반영이 되는 버그 수정
2. 좋아요 하트 모양 변경
3. 페이지네이션 버튼 모양, 글쓰기 버튼 모양 색상 변경
4. 글 수정, 글 삭제 버튼 사용자와 동일한 글에만 표시되게 프론트(template.py) 코드 수정
5. 글 수정, 글 삭제 로그인 유저와 동일한 경우에만 진행되게 백 (view.py) 코드 수정
6. 카드 모양 수정 (글씨크기, 작성시간 위치, 글 내용 2줄로 보이게, 카드 크기 610px -> 500px )
> fix : articles app 자유게시판 좋아요 버튼 버그 수정 및 자잘한 코드수정

- products/templates/products/index.html
- https://www.instagram.com/chickenkurly_regram/
- 하루에 한번씩 업데이트?
> feat : 인스타그램 피드 불러오기

- articles/templates/articles/detail.html
- articles/templates/articles/index.html
- articles/views.py
- templates/base.html
- 무한스크롤 vs 페이지네이션
- 하트 색상 보라색으로?
> style : articles 인덱스 페이지 디자인

- static/css/style.css
> fix : contentcard hover 해제 시 부자연스러운 동작 개선

- articles/templates/articles/search.html
- articles/urls.py
- articles/views.py
- templates/base.html
- product
상품명, 브랜드
- article
글 제목, 글 내용
> feat : 검색기능 구현

- accounts/forms.py
- accounts/templates/accounts/change_password.html
- accounts/templates/accounts/profile.html
- accounts/templates/accounts/profile_update.html
- accounts/views.py
> chore: 개인정보 form 수정

- products/templates/products/detail.html
- products/views.py
> feat(products) : 상품 문의 페이지네이션(5개) 구현

- accounts/templates/accounts/profile.html
> feat: 문의한 글-pagination

- accounts/templates/accounts/profile.html
- accounts/views.py
> chore: 회원정보-문의한 글 수정

- accounts/models.py
> feat: 회원정보-class user 수정

- products/templates/products/detail.html
- products/views.py
- static/js/product_inquiries.js
문의 생성은 비동기로 하면, 페이지네이션이 이상하게 되기 때문에 js 코드만 살리고 실제 적용은 하지 않았습니다.
> feat(products)  : 상품 문의 수정 및 삭제, 답변 생성 비동기

- articles/templates/articles/detail.html
- articles/templates/articles/recomment.html
- articles/urls.py
- articles/views.py
Dh 13 'chore : 자잘한 코드 수정'
1. 숫자나, 영문 댓글 작성시 라인 밖으로 나가지는 것 버그 수정
2. 대댓글 삭제 기능 추가
3. 글상세페이지, 댓글 상세페이지에서 뒤로가기 버튼 추가
> Dh 13 'chore : 자잘한 코드 수정'

- accounts/models.py
- products/templates/products/index.html
- static/css/style.css
인스타그램 불러오기, slider까지 직접 구현.. 뿌듯
> feat : 인스타그램 크롤링, slider 직접 구현

- accounts/models.py
chore: Django[admin]-username 수정
> chore: Django[admin]-username 수정

- accounts/admin.py
> feat: user model[admin] 등록

- accounts/models.py
> fix: signup

- accounts/templates/accounts/profile.html
> fix: 회원정보[등급]

- accounts/templates/accounts/profile.html
> chore: profile[ranking]

- accounts/models.py
- accounts/templates/accounts/profile.html
chore: accounts[profile] renew
> chore: accounts[profile] renew

- accounts/templates/accounts/profile.html
- accounts/urls.py
- accounts/views.py
chore: accounts[change password]
> chore: accounts[change password]

- accounts/templates/accounts/cart.html
- products/templates/products/detail.html
- products/views.py
- static/js/payment_detail.js
- templates/base.html
> feat(products) : 상품 detail에서 바로 결제하는 기능 구현

- accounts/forms.py
- accounts/templates/accounts/change_password.html
- accounts/templates/accounts/profile.html
- accounts/templates/accounts/profile_update.html
- accounts/views.py
> feat: change password 추가

- accounts/templates/accounts/profile.html
> done: profile[등급]

- static/css/footer.css
- static/js/footer.js
- templates/base.html
> style: base[footer] design

- static/js/footer.js
> fix: footer.js

- accounts/templates/accounts/cart.html
- accounts/templates/accounts/profile.html
- articles/templates/articles/detail.html
- products/templates/products/detail.html
- 장바구니 페이지에서 products detail로 url 연결
- articles index 페이지 `namespace`로 인한 오류 fix
- products detail 페이지 텍스트 겹치는 문제 ➡️ `<div>` 태그를 `<h1>` 태그로 수정
> style : design update

- templates/base.html
> chore: base[footer]

- articles/templates/articles/detail.html
chore : articles app 글 상세페이지에서 사진 모달 기능
1. 게시글 상세페이지에서 사진을 누르면 사진 모달창이 뜸
> chore : articles app 글 상세페이지에서 사진 모달 기능

- accounts/templates/accounts/signup.html
- articles/models.py
- articles/templates/articles/create.html
- articles/templates/articles/index.html
chore : 회원가입시 주소 필수입력 수정, 게시글 작성 제목 길이 수정
1. 회원가입시 주소를 입력안해도 다음진행 되었던것, 필수입력으로 수정
2. articles app에서 글 작성시 제목의 길이 30에서 20으로 수정
> chore : 회원가입시 주소 필수입력 수정, 게시글 작성 제목 길이 수정
